import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { CSSProperties, MouseEvent as ReactMouseEvent, PointerEvent as ReactPointerEvent } from 'react';
import { addEdge, applyEdgeChanges, applyNodeChanges, Background, BackgroundVariant, ConnectionLineType, ConnectionMode, Controls, MarkerType, ReactFlow, reconnectEdge, useReactFlow } from '@xyflow/react';
import type { Connection, EdgeChange, NodeChange, OnReconnect } from '@xyflow/react';
import { FiChevronDown, FiChevronsLeft, FiChevronsRight, FiCrosshair, FiMinus, FiPlus, FiSearch, FiSliders, FiTrash2, FiX } from 'react-icons/fi';
import { LuHand, LuMousePointer2, LuMoveRight } from 'react-icons/lu';
import { createShapeId, type Editor } from 'tldraw';
import { architectureCategoryIcons, architectureMeta, architectureVariants, getArchitectureNodeConnectionStates, getArchitectureNodeValidationIssues, getArchitectureVariant, getConnectionProtocol, renameArchitectureNode, validateArchitectureNodes, AUTOSAVE_KEY, VERSIONS_KEY, makeArchitectureNode, makeFreeAnchorNode, readArchitectureSnapshot, readArchitectureVersions, ArchitectureActionsContext, ArchitectureEdgeActionsContext, architectureEdgeTypes, architectureNodeTypes, ArchitectureSidebarGraph, TldrawArchitectureCanvas } from '../../../entities/architecture';
import type { ArchitectureEdge, ArchitectureNode, ArchitectureNodeKind, ArchitectureSnapshot, ArchitectureVersion, EdgeAnchor } from '../../../entities/architecture';
import { CanvasEventToast } from '../../../features/canvas-history';
import { evaluateArchitecture, TerminalLineText, toArchitecturePayload } from '../../../features/validate-architecture';
import { ArchitectureCommitsMenu, hasUncommittedArchitectureChanges } from '../../../features/version-architecture';
import type { Exercise, ValidationResult } from '../../../shared/types';

type TerminalLine = { kind: 'command'|'info'|'success'|'warning'|'error'|'pending'; text: string; runId?: number; warningCount?: number };
type CanvasEvent = { message: string; tone?: 'neutral'|'danger'; action?: 'undo'|'redo'; persistent?: boolean };

const solutions = [
  { id: 'direct-service', name: 'Direct Client → Service', description: 'The smallest valid request path for this requirement.', nodes: [{ kind: 'client' as const, variantId: 'web-browser', label: 'Web Browser' }, { kind: 'service' as const, variantId: 'go-http-api', label: 'Go HTTP API' }] },
  { id: 'load-balanced', name: 'Load Balancer Path', description: 'Routes traffic through a dedicated reverse proxy.', nodes: [{ kind: 'client' as const, variantId: 'web-browser', label: 'Web Browser' }, { kind: 'load-balancer' as const, variantId: 'nginx', label: 'NGINX' }, { kind: 'service' as const, variantId: 'go-http-api', label: 'Go HTTP API' }] },
];
export function SystemDesignLabPage() {
  const start = useMemo(readArchitectureSnapshot, []); const [nodes,setNodes]=useState(start.nodes); const [edges,setEdges]=useState(start.edges);
  const [exercise,setExercise]=useState<Exercise|null>(null); const [results,setResults]=useState<ValidationResult[]>([]); const [error,setError]=useState<string|null>(null); const [validating,setValidating]=useState(false); const [terminal,setTerminal]=useState<TerminalLine[]>([]);
  const [nodeValidationVisible,setNodeValidationVisible]=useState(false);
  const [workspaceView,setWorkspaceView]=useState<'canvas'|'solutions'>('canvas'); const [selectedSolutionId,setSelectedSolutionId]=useState(solutions[0].id);
  const [requirementsCollapsed,setRequirementsCollapsed]=useState(false); const [requirementsExpanded,setRequirementsExpanded]=useState(true); const [layersExpanded,setLayersExpanded]=useState(true);
  const [draftArrow,setDraftArrow]=useState<{start:{x:number;y:number};current:{x:number;y:number}}|null>(null);
  const [dropTargetId,setDropTargetId]=useState<string|null>(null);
  const [isReconnecting,setIsReconnecting]=useState(false);
  const [reconnectCursor,setReconnectCursor]=useState<{x:number;y:number}|null>(null);
  const [registryOpen,setRegistryOpen]=useState(false); const [query,setQuery]=useState(''); const [group,setGroup]=useState<ArchitectureNodeKind|null>(null); const [groupQuery,setGroupQuery]=useState('');
  const [inspectorId,setInspectorId]=useState<string|null>(null); const [menu,setMenu]=useState<{id:string;x:number;y:number}|null>(null);
  const [canvasEvent,setCanvasEvent]=useState<CanvasEvent|null>(null);
  const [versions,setVersions]=useState<ArchitectureVersion[]>(readArchitectureVersions); const [versionsOpen,setVersionsOpen]=useState(false); const [sidebarWidth,setSidebarWidth]=useState(380); const [runnerHeight,setRunnerHeight]=useState(270); const [resize,setResize]=useState<'sidebar'|'runner'|null>(null);
  const [tool,setTool]=useState<'hand'|'selection'|'connection'>('selection'); const [isPanning,setIsPanning]=useState(false); const history=useRef<ArchitectureSnapshot[]>([]); const future=useRef<ArchitectureSnapshot[]>([]); const run=useRef(0); const terminalRef=useRef<HTMLDivElement|null>(null); const searchRef=useRef<HTMLInputElement|null>(null); const autosaveTimer=useRef<number|null>(null); const canvasEventTimer=useRef<number|null>(null); const dragArchitectureSnapshot=useRef<ArchitectureSnapshot|null>(null); const connectionStart=useRef<{nodeId:string;handleId:string|null}|null>(null); const connectionPointer=useRef<{clientX:number;clientY:number}|null>(null); const reconnecting=useRef(false); const handPan=useRef<{start:{x:number;y:number;};viewport:{x:number;y:number;zoom:number}}|null>(null); const tldrawEditor=useRef<Editor|null>(null);
  const flow=useReactFlow<ArchitectureNode,ArchitectureEdge>(); const usesCommand=useMemo(()=>/Macintosh|Mac OS X/.test(navigator.userAgent),[]);
  const nodeConnectionStates=useMemo(()=>getArchitectureNodeConnectionStates(nodes,edges),[nodes,edges]);
  const nodeValidationStates=useMemo(()=>validateArchitectureNodes(nodes,edges),[nodes,edges]);
  const hasUncommittedChanges=useMemo(()=>hasUncommittedArchitectureChanges({nodes,edges},versions[0]),[nodes,edges,versions]);
  const visibleNodeValidationIssues=useMemo(()=>workspaceView==='canvas'&&nodeValidationVisible?getArchitectureNodeValidationIssues(nodeValidationStates):[],[nodeValidationStates,nodeValidationVisible,workspaceView]);
  const runnerStatus=validating?'running':error||results.some(result=>result.status==='failed')||visibleNodeValidationIssues.some(issue=>issue.severity==='error')?'error':visibleNodeValidationIssues.length?'warning':'ready';
  const snapshot=useCallback(():ArchitectureSnapshot=>({nodes:structuredClone(nodes),edges:structuredClone(edges)}),[nodes,edges]);
  const record=useCallback(()=>{history.current.push(snapshot());future.current=[]},[snapshot]);
  const showCanvasEvent=useCallback((event:CanvasEvent)=>{if(canvasEventTimer.current)window.clearTimeout(canvasEventTimer.current);canvasEventTimer.current=null;setCanvasEvent(event);if(!event.persistent)canvasEventTimer.current=window.setTimeout(()=>setCanvasEvent(null),4500)},[]);
  const undoLastChange=useCallback(()=>{const previous=history.current.pop();if(!previous)return;future.current.push(snapshot());setNodes(previous.nodes);setEdges(previous.edges);setMenu(null);setInspectorId(null);showCanvasEvent({message:'Last change undone',action:'redo',persistent:true})},[showCanvasEvent,snapshot]);
  const redoLastChange=useCallback(()=>{const next=future.current.pop();if(!next)return;history.current.push(snapshot());setNodes(next.nodes);setEdges(next.edges);setMenu(null);setInspectorId(null);showCanvasEvent({message:'Change restored',action:'undo'})},[showCanvasEvent,snapshot]);
  const edgeFor=useCallback((connection:Connection):ArchitectureEdge|null=>{ if(!connection.source||!connection.target)return null; const source=nodes.find(n=>n.id===connection.source); if(!source)return null; const p=source.data.isAnchor?'HTTP':getConnectionProtocol(source.data.kind); return {id:`edge-${crypto.randomUUID()}`,source:connection.source,target:connection.target,sourceHandle:connection.sourceHandle,targetHandle:connection.targetHandle,type:'architecture',data:{protocol:p},label:p,markerEnd:{type:MarkerType.ArrowClosed,color:'#91a4c0'},style:{stroke:'#91a4c0',strokeWidth:1.5},reconnectable:true}; },[nodes]);
  const handleFacing=useCallback((position:{x:number;y:number},otherId:string)=>{const other=nodes.find(node=>node.id===otherId);if(!other)return 'left';const x=other.position.x+(other.measured?.width??0)/2;const y=other.position.y+(other.measured?.height??0)/2;const dx=x-position.x,dy=y-position.y;return Math.abs(dx)>=Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'top':'bottom')},[nodes]);
  const updateVariant=useCallback((id:string,variantId:string)=>{record();setNodes(ns=>ns.map(n=>n.id===id?{...n,data:{...n.data,variantId}}:n));showCanvasEvent({message:'Component type changed',action:'undo'})},[record,showCanvasEvent]);
  const renameNode=useCallback((id:string,label:string)=>{const next=renameArchitectureNode(nodes,id,label);if(next===nodes)return;record();setNodes(next);showCanvasEvent({message:`Renamed to “${label}”`,action:'undo'})},[nodes,record,showCanvasEvent]);
  const reportCanvasRename=useCallback((_id:string,label:string)=>{record();showCanvasEvent({message:`Renamed to “${label}”`,action:'undo'})},[record,showCanvasEvent]);
  const openMenu=useCallback((id:string,e:ReactMouseEvent)=>{e.preventDefault();e.stopPropagation();setMenu({id,x:e.clientX,y:e.clientY})},[]);
  const clearDropSelection=()=>requestAnimationFrame(()=>setNodes(current=>current.map(node=>node.selected?{...node,selected:false}:node)));
  const nodeDropTarget=(clientX:number,clientY:number)=>{const element=document.elementsFromPoint(clientX,clientY).find(item=>item.classList.contains('react-flow__node')) as HTMLElement|undefined;if(!element||element.querySelector('.free-anchor-node'))return null;const id=element.dataset.id;if(!id)return null;const rect=element.getBoundingClientRect();const distances={left:Math.abs(clientX-rect.left),right:Math.abs(rect.right-clientX),top:Math.abs(clientY-rect.top),bottom:Math.abs(rect.bottom-clientY)};const side=(Object.entries(distances).sort((a,b)=>a[1]-b[1])[0]?.[0]??'left') as EdgeAnchor['side'];const rawOffset=side==='left'||side==='right'?(clientY-rect.top)/rect.height:(clientX-rect.left)/rect.width;return{id,anchor:{side,offset:Math.min(.94,Math.max(.06,rawOffset))} satisfies EdgeAnchor}};

  useEffect(()=>{fetch('/api/exercise').then(r=>r.json()).then(setExercise).catch((e:Error)=>setError(e.message))},[]);
  useEffect(()=>()=>{if(canvasEventTimer.current)window.clearTimeout(canvasEventTimer.current)},[]);
  useEffect(()=>{const referenced=new Set(edges.flatMap(edge=>[edge.source,edge.target]));setNodes(current=>{const next=current.filter(node=>!node.data.isAnchor||referenced.has(node.id));return next.length===current.length?current:next})},[edges]);
  useEffect(()=>{if(autosaveTimer.current)clearTimeout(autosaveTimer.current);autosaveTimer.current=window.setTimeout(()=>localStorage.setItem(AUTOSAVE_KEY,JSON.stringify({nodes,edges})),400);return()=>{if(autosaveTimer.current)clearTimeout(autosaveTimer.current)}},[nodes,edges]);
  useEffect(()=>{terminalRef.current?.scrollTo({top:terminalRef.current.scrollHeight})},[terminal,validating]);
  useEffect(()=>{if(!menu)return;const close=()=>setMenu(null);window.addEventListener('pointerdown',close);return()=>window.removeEventListener('pointerdown',close)},[menu]);
  useEffect(()=>{if(!resize)return;const move=(e:PointerEvent)=>resize==='sidebar'?setSidebarWidth(Math.min(560,Math.max(300,e.clientX))):setRunnerHeight(Math.min(500,Math.max(170,innerHeight-e.clientY)));const up=()=>setResize(null);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});window.addEventListener('pointercancel',up,{once:true});return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up)}},[resize]);
  useEffect(()=>{const move=(event:PointerEvent)=>{if(!reconnecting.current&&!connectionStart.current)return;connectionPointer.current={clientX:event.clientX,clientY:event.clientY};if(reconnecting.current)setReconnectCursor({x:event.clientX,y:event.clientY});setDropTargetId(nodeDropTarget(event.clientX,event.clientY)?.id??null)};window.addEventListener('pointermove',move);return()=>window.removeEventListener('pointermove',move)},[]);
  useEffect(()=>{const keys=(e:KeyboardEvent)=>{const command=e.metaKey||e.ctrlKey;if(e.key==='Escape'){setTool('selection');setDraftArrow(null);setMenu(null);setInspectorId(null);return}if(command&&e.key.toLowerCase()==='k'){e.preventDefault();setRequirementsCollapsed(false);setRegistryOpen(true);requestAnimationFrame(()=>searchRef.current?.focus());return}if(command&&e.key==='Enter'){e.preventDefault();void validate();return}if(command&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();if(e.shiftKey)redoLastChange();else undoLastChange();return}if(!e.metaKey&&!e.ctrlKey&&!e.altKey&&['1','2','3'].includes(e.key)){setTool(e.key==='1'?'hand':e.key==='2'?'selection':'connection')}};window.addEventListener('keydown',keys,true);return()=>window.removeEventListener('keydown',keys,true)},[nodes,edges,workspaceView,selectedSolutionId,validating,redoLastChange,undoLastChange]);

  const onNodesChange=useCallback((changes:NodeChange<ArchitectureNode>[])=>setNodes(ns=>applyNodeChanges(changes,ns)),[]); const onEdgesChange=useCallback((changes:EdgeChange<ArchitectureEdge>[])=>setEdges(es=>applyEdgeChanges(changes,es).map(edge=>({...edge,zIndex:edge.selected?1000:0}))),[]);
  const onConnect=useCallback((c:Connection)=>{if(reconnecting.current)return;const edge=edgeFor(c);if(edge){record();setEdges(es=>addEdge(edge,es))}},[edgeFor,record]);
  const onConnectEnd=(event:MouseEvent|TouchEvent,connectionState:{isValid:boolean|null})=>{const start=connectionStart.current;connectionStart.current=null;setDropTargetId(null);clearDropSelection();if(reconnecting.current||connectionState.isValid||!start)return;const eventPoint='changedTouches' in event?event.changedTouches[0]:event;const point=connectionPointer.current??eventPoint;connectionPointer.current=null;if(!point)return;const target=nodeDropTarget(point.clientX,point.clientY);if(target&&target.id!==start.nodeId){const created=edgeFor({source:start.nodeId,sourceHandle:start.handleId,target:target.id,targetHandle:null});if(created){const edge={...created,targetHandle:`${created.id}-target`,data:{...created.data!,targetAnchor:target.anchor}};record();setEdges(current=>[...current,edge])}return}const position=flow.screenToFlowPosition({x:point.clientX,y:point.clientY});const anchor=makeFreeAnchorNode(position.x,position.y);const edge=edgeFor({source:start.nodeId,sourceHandle:start.handleId,target:anchor.id,targetHandle:handleFacing(position,start.nodeId)});if(!edge)return;record();setNodes(current=>[...current,anchor]);setEdges(current=>[...current,edge])};
  const onReconnect=useCallback<OnReconnect<ArchitectureEdge>>((oldEdge,c)=>{const generated=edgeFor(c);setEdges(es=>reconnectEdge(oldEdge,c,es).map(e=>e.id===oldEdge.id?{...e,label:generated?.label,data:{protocol:generated?.data?.protocol??oldEdge.data?.protocol??'',sourceAnchor:c.sourceHandle===`${oldEdge.id}-source`?oldEdge.data?.sourceAnchor:undefined,targetAnchor:c.targetHandle===`${oldEdge.id}-target`?oldEdge.data?.targetAnchor:undefined}}:e))},[edgeFor]);
  const onReconnectEnd=(event:MouseEvent|TouchEvent,edge:ArchitectureEdge,stationaryHandle:'source'|'target',connectionState:{isValid:boolean|null})=>{connectionStart.current=null;setDropTargetId(null);setIsReconnecting(false);setReconnectCursor(null);clearDropSelection();window.setTimeout(()=>{reconnecting.current=false},50);if(connectionState.isValid)return;const eventPoint='changedTouches' in event?event.changedTouches[0]:event;const point=connectionPointer.current??eventPoint;connectionPointer.current=null;if(!point)return;const target=nodeDropTarget(point.clientX,point.clientY);const fixedId=stationaryHandle==='target'?edge.target:edge.source;if(target&&target.id!==fixedId){const detachedId=stationaryHandle==='target'?edge.source:edge.target;setNodes(current=>current.filter(node=>node.id!==detachedId||!node.data.isAnchor));setEdges(current=>current.map(item=>item.id!==edge.id?item:stationaryHandle==='target'?{...item,source:target.id,sourceHandle:`${edge.id}-source`,data:{...item.data!,sourceAnchor:target.anchor,bend:undefined}}:{...item,target:target.id,targetHandle:`${edge.id}-target`,data:{...item.data!,targetAnchor:target.anchor,bend:undefined}}));return}const position=flow.screenToFlowPosition({x:point.clientX,y:point.clientY});const anchor=makeFreeAnchorNode(position.x,position.y);const detachedId=stationaryHandle==='target'?edge.source:edge.target;setNodes(current=>[...current.filter(node=>node.id!==detachedId||!node.data.isAnchor),anchor]);setEdges(current=>current.map(item=>item.id!==edge.id?item:stationaryHandle==='target'?{...item,source:anchor.id,sourceHandle:handleFacing(position,edge.target),data:{...item.data!,sourceAnchor:undefined,bend:undefined}}:{...item,target:anchor.id,targetHandle:handleFacing(position,edge.source),data:{...item.data!,targetAnchor:undefined,bend:undefined}}))};
  const finishFreeArrow=(event:ReactPointerEvent<HTMLDivElement>)=>{if(!draftArrow)return;const distance=Math.hypot(event.clientX-draftArrow.start.x,event.clientY-draftArrow.start.y);if(distance>8){record();const start=flow.screenToFlowPosition(draftArrow.start);const end=flow.screenToFlowPosition({x:event.clientX,y:event.clientY});const source=makeFreeAnchorNode(start.x,start.y);const target=makeFreeAnchorNode(end.x,end.y);const edge:ArchitectureEdge={id:`edge-${crypto.randomUUID()}`,source:source.id,target:target.id,sourceHandle:'right',targetHandle:'left',type:'architecture',data:{protocol:''},markerEnd:{type:MarkerType.ArrowClosed,color:'#91a4c0'},style:{stroke:'#91a4c0',strokeWidth:1.5},reconnectable:true};setNodes(current=>[...current,source,target]);setEdges(current=>[...current,edge])}setDraftArrow(null)};
  const addNode=(kind:ArchitectureNodeKind,variantId='abstract')=>{record();const kindCount=nodes.filter(n=>!n.data.isAnchor&&n.data.kind===kind).length+1;const total=nodes.filter(n=>!n.data.isAnchor).length;const v=getArchitectureVariant(kind,variantId);const node=makeArchitectureNode(kind,variantId,100+(total%3)*280,140+Math.floor(total/3)*150,kindCount===1?v.label:`${v.label} ${kindCount}`);setNodes(ns=>[...ns,node]);setRegistryOpen(false);setGroup(null);showCanvasEvent({message:`Added “${node.data.label}”`,action:'undo'});window.setTimeout(()=>{const editor=tldrawEditor.current;if(!editor)return;const id=createShapeId(node.id),bounds=editor.getShapePageBounds(id);editor.select(id);if(bounds)editor.zoomToBounds(bounds,{animation:{duration:220},inset:140,targetZoom:1})},0)};
  const deleteNode=(id:string)=>{const label=nodes.find(node=>node.id===id)?.data.label??'Component';record();setNodes(ns=>ns.filter(n=>n.id!==id));setEdges(es=>es.filter(e=>e.source!==id&&e.target!==id));setMenu(null);if(inspectorId===id)setInspectorId(null);showCanvasEvent({message:`Deleted “${label}”`,tone:'danger',action:'undo'})};
  const focusNode=(id:string)=>{setNodes(ns=>ns.map(n=>({...n,selected:n.id===id})));const editor=tldrawEditor.current;if(editor){const shapeId=createShapeId(id),bounds=editor.getShapePageBounds(shapeId);editor.select(shapeId);if(bounds)editor.zoomToBounds(bounds,{animation:{duration:220},inset:140,targetZoom:1})}};
  const startResize=(panel:'sidebar'|'runner',event:ReactPointerEvent<HTMLDivElement>)=>{event.preventDefault();window.getSelection()?.removeAllRanges();setResize(panel)};
  const commitArchitecture=()=>{const v:ArchitectureVersion={id:crypto.randomUUID(),name:`Commit ${versions.length+1}`,createdAt:new Date().toISOString(),...snapshot()};const next=[v,...versions];setVersions(next);localStorage.setItem(VERSIONS_KEY,JSON.stringify(next));setVersionsOpen(true);showCanvasEvent({message:`Committed “${v.name}”`})};
  const renameArchitectureVersion=(versionId:string,name:string)=>{setVersions(current=>{const next=current.map(version=>version.id===versionId?{...version,name}:version);localStorage.setItem(VERSIONS_KEY,JSON.stringify(next));return next});showCanvasEvent({message:`Renamed commit to “${name}”`})};
  const deleteLatestArchitectureVersion=()=>{const latest=versions[0];if(!latest)return;const next=versions.slice(1);setVersions(next);localStorage.setItem(VERSIONS_KEY,JSON.stringify(next));showCanvasEvent({message:`Deleted commit “${latest.name}”`,tone:'danger'})};
  const restoreArchitectureVersion=(v:ArchitectureVersion)=>{record();setNodes(v.nodes);setEdges(v.edges);setVersionsOpen(false);setWorkspaceView('canvas');showCanvasEvent({message:`Restored “${v.name}”`,action:'undo'});window.setTimeout(()=>tldrawEditor.current?.zoomToFit({animation:{duration:220}}),0)};
  const validate=async()=>{
    const solution=solutions.find(s=>s.id===selectedSolutionId)??solutions[0];
    const architecture=workspaceView==='solutions'
      ?{nodes:solution.nodes.map((n,i)=>({id:`${solution.id}-${i}`,kind:n.kind})),edges:solution.nodes.slice(1).map((_,i)=>({from:`${solution.id}-${i}`,to:`${solution.id}-${i+1}`}))}
      :toArchitecturePayload(nodes,edges);
    const path=workspaceView==='solutions'?`./solutions/${solution.id}`:'./architecture';
    const nodeIssues=workspaceView==='canvas'?getArchitectureNodeValidationIssues(nodeValidationStates):[];
    const nodeErrors=nodeIssues.filter(issue=>issue.severity==='error');
    const nodeWarnings=nodeIssues.filter(issue=>issue.severity==='warning');
    if(workspaceView==='canvas')setNodeValidationVisible(true);
    const id=++run.current;
    setValidating(true);setResults([]);setError(null);
    setTerminal(t=>[...t,...(t.length?[{kind:'info' as const,text:''}]:[]),{kind:'info',text:`── validation run ${String(id).padStart(2,'0')} ──`,runId:id},{kind:'command',text:`$ archlab validate ${path}`,runId:id},{kind:'pending',text:'contacting validation engine',runId:id}]);
    try{
      const r=await evaluateArchitecture(architecture);
      const lb=architecture.nodes.some(n=>n.kind==='load-balancer');
      const lines:TerminalLine[]=[
        {kind:'command',text:`$ archlab build ${path}`},
        {kind:'success',text:`✓ Parsed topology: ${architecture.nodes.length} component${architecture.nodes.length===1?'':'s'}, ${architecture.edges.length} connection${architecture.edges.length===1?'':'s'}`},
        {kind:'success',text:'✓ Architecture manifest compiled'},
        {kind:'command',text:`$ archlab lint ${path} --nodes`},
      ];
      if(nodeIssues.length){
        lines.push({kind:nodeErrors.length?'error':'warning',text:`${nodeErrors.length?'✕':'⚠'} Node validation found ${nodeIssues.length} issue${nodeIssues.length===1?'':'s'}`});
        for(const issue of nodeIssues)lines.push(
          {kind:issue.severity,text:`  ${issue.severity==='error'?'✕':'⚠'} [${issue.code}] ${issue.message}`},
          {kind:'info',text:`      ↳ ${issue.suggestion}`},
        );
      }else lines.push({kind:'success',text:'✓ All component connection contracts satisfied'});
      lines.push({kind:'command',text:'$ archlab deploy --target simulator  # simulated'},{kind:'success',text:'✓ Runtime sandbox ready'});
      if(!lb)lines.push({kind:'warning',text:'⚠ No load balancer configured (optional)'});
      lines.push({kind:'command',text:'$ archlab test --requirements  # server'});
      r.forEach(x=>lines.push({kind:x.status==='passed'?'success':'error',text:`${x.status==='passed'?'✓':'✕'} ${exercise?.requirement.title??x.requirementId}`},{kind:'info',text:`  ${x.message}`}));
      const serverFailures=r.filter(x=>x.status==='failed').length;
      const failed=serverFailures+nodeErrors.length;
      const passed=r.filter(x=>x.status==='passed').length;
      const warningCount=nodeWarnings.length+(lb?0:1);
      lines.push({kind:failed?'error':'success',text:failed?`FAIL  ${failed} error${failed===1?'':'s'} · ${passed} passed · ${warningCount} warning${warningCount===1?'':'s'}`:`PASS  ${passed} passed · ${warningCount} warning${warningCount===1?'':'s'}`,warningCount});
      setTerminal(t=>[...t.filter(x=>!(x.runId===id&&x.kind==='pending')),...lines]);setResults(r);
    }catch(e){setError(e instanceof Error?e.message:'Validation failed')}finally{setValidating(false)}
  };

  const searchResults=useMemo(()=>{const q=query.trim().toLowerCase();return q?(Object.keys(architectureVariants) as ArchitectureNodeKind[]).flatMap(k=>architectureVariants[k].filter(v=>`${v.label} ${v.description} ${v.type}`.toLowerCase().includes(q)).map(v=>({kind:k,v}))):[]},[query]);
  const updateEdgeBend=useCallback((id:string,bend:{along:number;normal:number})=>setEdges(current=>current.map(edge=>edge.id===id?{...edge,data:{protocol:edge.data?.protocol??'',bend}}:edge)),[]);
  const edgeEndpointIds=useMemo(()=>new Set(edges.filter(edge=>edge.selected).flatMap(edge=>[edge.source,edge.target])),[edges]);
  const endpointHandles=useMemo(()=>{const map=new Map<string,Array<EdgeAnchor&{id:string;type:'source'|'target'}>>();const add=(nodeId:string,handle:EdgeAnchor&{id:string;type:'source'|'target'})=>map.set(nodeId,[...(map.get(nodeId)??[]),handle]);for(const edge of edges){if(edge.data?.sourceAnchor)add(edge.source,{...edge.data.sourceAnchor,id:`${edge.id}-source`,type:'source'});if(edge.data?.targetAnchor)add(edge.target,{...edge.data.targetAnchor,id:`${edge.id}-target`,type:'target'})}return map},[edges]);
  const solution=solutions.find(s=>s.id===selectedSolutionId)??solutions[0];
  return <main className="app-shell" onContextMenu={event=>event.preventDefault()}><section className={`workspace ${requirementsCollapsed?'workspace--requirements-collapsed':''} ${resize?'workspace--resizing':''}`} style={{'--sidebar-width':`${sidebarWidth}px`} as CSSProperties}>
    <aside className={`panel requirements-panel ${requirementsCollapsed?'requirements-panel--collapsed':''}`}><div className="panel-heading">{!requirementsCollapsed&&<nav className="sidebar-view-tabs" aria-label="Task views"><button className={workspaceView==='canvas'?'sidebar-view-tab--active':''} onClick={()=>setWorkspaceView('canvas')}>Description</button><button className={workspaceView==='solutions'?'sidebar-view-tab--active':''} onClick={()=>setWorkspaceView('solutions')}>Solutions</button></nav>}<button className="collapse-button" onClick={()=>setRequirementsCollapsed(v=>!v)} aria-label={requirementsCollapsed?'Expand requirements':'Collapse requirements'}>{requirementsCollapsed?<FiChevronsRight/>:<FiChevronsLeft/>}</button></div>
    {!requirementsCollapsed&&(workspaceView==='solutions'?<div className="solutions-sidebar"><div><span className="panel-id">REFERENCE SOLUTIONS</span><p>Open a known-good architecture on the canvas and validate it.</p></div><div className="solutions-sidebar__list">{solutions.map(s=><button key={s.id} className={s.id===solution.id?'solution-option--active':''} onClick={()=>setSelectedSolutionId(s.id)}><strong>{s.name}</strong><small>{s.description}</small></button>)}</div><button className="back-to-canvas-button" onClick={()=>setWorkspaceView('canvas')}><FiChevronsLeft/> Back to My Canvas</button></div>:<>
      <div className="sidebar-section requirements-section"><button className="sidebar-section-toggle" onClick={()=>setRequirementsExpanded(v=>!v)}><span className="panel-id">REQUIREMENTS</span><span className="problem-status"><i/> Unsolved</span>{requirementsExpanded?<FiChevronDown/>:<FiChevronsRight/>}</button>{requirementsExpanded&&<div className="requirements-content"><h2>Route web traffic to an HTTP API</h2><p className="lead">A browser request must reach an HTTP handler through the architecture you build.</p><h3>Request contract</h3><ul className="requirement-list"><li><strong>Entry point:</strong> Web Browser</li><li><strong>Request:</strong> <code>GET /{'{path}'}</code></li><li><strong>Transport:</strong> <code>HTTPS</code></li><li><strong>Target capability:</strong> <code>http.handle</code></li><li><strong>Assertion:</strong> <code>path.exists</code></li></ul><h3>Acceptance rule</h3><pre className="acceptance-rule"><code><i>path</i>(source: http.request, target: http.handle) == <b>true</b></code></pre></div>}</div>
      <div className="sidebar-section layers"><ArchitectureSidebarGraph nodes={nodes} edges={edges} connectionStates={nodeConnectionStates} validationStates={nodeValidationVisible?nodeValidationStates:undefined} expanded={layersExpanded} onToggleExpanded={()=>setLayersExpanded(v=>!v)} onAddComponent={()=>{setRegistryOpen(true);requestAnimationFrame(()=>searchRef.current?.focus())}} onFocus={focusNode} onRename={renameNode} onOpenMenu={(id,x,y)=>setMenu({id,x,y})}/></div>
      {registryOpen&&<div className="component-spotlight-backdrop" onPointerDown={()=>setRegistryOpen(false)}><div className="sidebar-section catalog component-library" role="dialog" aria-label="Component library" onPointerDown={e=>e.stopPropagation()}><div className="component-library__header"><div><span className="panel-id">COMPONENT LIBRARY</span><p>Search or browse by category</p></div><button onClick={()=>setRegistryOpen(false)} aria-label="Close component library"><FiX/></button></div><label className="catalog-search"><FiSearch/><input ref={searchRef} placeholder="Search components…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></label>{query.trim()?<div className="component-picker search-results">{searchResults.map(({kind,v})=>{const I=v.icon;return <button className="component-option" key={`${kind}-${v.id}`} onClick={()=>addNode(kind,v.id)}><I/><span><strong>{v.label}</strong><small>{v.description}</small></span><em>{architectureMeta[kind].group}</em></button>})}</div>:<div className="registry-categories">{(Object.keys(architectureVariants) as ArchitectureNodeKind[]).map(k=>{const I=architectureCategoryIcons[k];return <div className={`registry-group ${group===k?'registry-group--active':''}`} key={k}><div className="registry-category"><button className="registry-category-main" onClick={()=>setGroup(g=>g===k?null:k)}><I/><span><strong>{architectureMeta[k].group}</strong><small>Browse concrete components</small></span></button><button className="registry-add" onClick={()=>addNode(k)} aria-label={`Quick add ${architectureMeta[k].group}`} title={`Quick add generic ${architectureMeta[k].group.toLowerCase()}`}><FiPlus/></button><button className="registry-expand" onClick={()=>setGroup(g=>g===k?null:k)} aria-label={`Browse ${architectureMeta[k].group}`}>{group===k?<FiChevronDown/>:<FiChevronsRight/>}</button></div>{group===k&&<div className="component-picker component-picker--inline"><label className="group-search"><FiSearch/><input value={groupQuery} onChange={e=>setGroupQuery(e.target.value)} placeholder={`Search ${architectureMeta[k].group.toLowerCase()}…`}/></label>{architectureVariants[k].filter(v=>v.concrete&&`${v.label} ${v.description}`.toLowerCase().includes(groupQuery.toLowerCase())).map(v=>{const V=v.icon;return <button className="component-option" key={v.id} onClick={()=>addNode(k,v.id)}><V/><span><strong>{v.label}</strong><small>{v.description}</small></span><em>specific</em></button>})}</div>}</div>})}</div>}</div></div>}
      {menu&&<div className="context-menu" style={{left:menu.x,top:menu.y}} onPointerDown={e=>e.stopPropagation()}><button onClick={()=>{focusNode(menu.id);setMenu(null)}}><FiCrosshair/>Focus on canvas</button><button onClick={()=>{setInspectorId(menu.id);focusNode(menu.id);setMenu(null)}}><FiSliders/>Inspect component</button><button className="context-menu__danger" onClick={()=>deleteNode(menu.id)}><FiTrash2/>Delete component</button></div>}
    </>)}</aside>
    {!requirementsCollapsed&&<div className={`panel-resizer panel-resizer--vertical ${resize==='sidebar'?'panel-resizer--active':''}`} onPointerDown={event=>startResize('sidebar',event)}/>}<div className="workbench" style={{'--runner-height':`${runnerHeight}px`} as CSSProperties}><section className="canvas-panel">
      {workspaceView==='canvas'&&<ArchitectureCommitsMenu versions={versions} dirty={hasUncommittedChanges} open={versionsOpen} onOpenChange={setVersionsOpen} onCommit={commitArchitecture} onRestore={restoreArchitectureVersion} onRename={renameArchitectureVersion} onDeleteLatest={deleteLatestArchitectureVersion}/>}
      <div className={`canvas flow-canvas ${workspaceView==='solutions'?'canvas--behind-solutions':''}`} onContextMenu={event=>event.preventDefault()}>
        <TldrawArchitectureCanvas nodes={nodes} edges={edges} tool={tool} inspectorId={inspectorId} validationStates={nodeValidationVisible?nodeValidationStates:undefined} onNodesChange={setNodes} onEdgesChange={setEdges} onMountEditor={editor=>{tldrawEditor.current=editor}} onToolChange={setTool} onCloseInspector={()=>setInspectorId(null)} onUpdateVariant={updateVariant} onNodeRenamed={reportCanvasRename}/>
        <div className="flow-tools" role="toolbar"><button className={tool==='hand'?'active':''} onClick={()=>setTool('hand')} title="Pan canvas — 1"><LuHand/><small>1</small></button><button className={tool==='selection'?'active':''} onClick={()=>setTool('selection')} title="Select — 2"><LuMousePointer2/><small>2</small></button><button className={tool==='connection'?'active':''} onClick={()=>setTool('connection')} title="Connect — 3"><LuMoveRight/><small>3</small></button></div>
        <div className="canvas-zoom-controls"><button onClick={()=>tldrawEditor.current?.zoomOut(undefined,{animation:{duration:120}})} title="Zoom out"><FiMinus/></button><button onClick={()=>tldrawEditor.current?.zoomToFit({animation:{duration:160}})} title="Fit canvas"><FiCrosshair/></button><button onClick={()=>tldrawEditor.current?.zoomIn(undefined,{animation:{duration:120}})} title="Zoom in"><FiPlus/></button></div>
      </div>
      {workspaceView==='canvas'&&canvasEvent&&<CanvasEventToast message={canvasEvent.message} tone={canvasEvent.tone} actionLabel={canvasEvent.action==='undo'?'Undo':canvasEvent.action==='redo'?'Redo':undefined} onAction={canvasEvent.action==='undo'?undoLastChange:canvasEvent.action==='redo'?redoLastChange:undefined}/>}
      {workspaceView==='solutions'&&<div className="solutions-view"><section className="solution-preview"><button className="solution-back-button" onClick={()=>setWorkspaceView('canvas')}><FiChevronsLeft/> Back to My Canvas</button><div className="solution-preview__heading"><span className="panel-id">SOLUTION</span><h2>{solution.name}</h2><p>{solution.description}</p></div><div className="solution-path">{solution.nodes.map((n,i)=>{const v=getArchitectureVariant(n.kind,n.variantId),I=v.icon;return <div className="solution-step" key={`${solution.id}-${n.kind}`}>{i>0&&<span className="solution-connection"><small>{getConnectionProtocol(solution.nodes[i-1].kind)}</small><span className="solution-arrow">→</span></span>}<div className={`solution-node solution-node--${n.kind}`}><I/><span><strong>{n.label}</strong><small>{architectureMeta[n.kind].role}</small></span></div></div>})}</div></section></div>}
    </section><div className={`panel-resizer panel-resizer--horizontal ${resize==='runner'?'panel-resizer--active':''}`} onPointerDown={event=>startResize('runner',event)}/><section className="panel validation-panel validation-terminal"><div className="validation-header"><div className="validation-title"><span className="panel-id">TEST RUNNER</span><i className={`validation-dot validation-dot--${runnerStatus}`}/></div><div className="validation-actions"><button className="clear-terminal-button" onClick={()=>{setTerminal([]);setError(null)}} disabled={validating||!terminal.length}><FiTrash2/></button><button className="validate-button" onClick={()=>void validate()} disabled={validating}><span>{validating?'Running…':'▶ Validate'}</span><kbd><span>{usesCommand?'⌘':'Ctrl'}</span><span>↵</span></kbd></button></div></div><div className="validation-body">{error&&<div className="error-card">{error}</div>}<div ref={terminalRef} className={`terminal-output ${!terminal.length?'terminal-output--idle':''}`}>{!terminal.length&&<><p className="terminal-line terminal-line--info">archlab simulator v0.3 · tldraw</p><p className="terminal-line terminal-line--info">› topology loaded</p><p className="terminal-cursor">▋</p></>}{terminal.map((l,i)=><p key={`${i}-${l.text}`} className={`terminal-line terminal-line--${l.kind}`}>{l.kind==='pending'&&<span className="terminal-spinner"/>}<TerminalLineText text={l.text} warningCount={l.warningCount}/></p>)}</div></div></section></div>
  </section></main>;
}
